#this script imports the large CSV and makes graphs.
setwd("C://Users//insan_000//Documents//summer 2018//simulation data//bigg data")
library(tidyverse)

dfr = read_csv("all_averages_for_SNP_sim_1000.csv")
dfr$Kappa = as.factor(dfr$Kappa)
dfr$`GC%` = as.factor(dfr$`GC%`)

dfrset0 = subset(dfr, dfr$`GC%` == 0)
dfrset1 = subset(dfr, dfr$`GC%` == 0.1)
dfrset2 = subset(dfr, dfr$`GC%` == 0.2)
dfrset3 = subset(dfr, dfr$`GC%` == 0.3)
dfrset4 = subset(dfr, dfr$`GC%` == 0.4)
dfrset5 = subset(dfr, dfr$`GC%` == 0.5)
dfrset6 = subset(dfr, dfr$`GC%` == 0.6)
dfrset7 = subset(dfr, dfr$`GC%` == 0.7)
dfrset8 = subset(dfr, dfr$`GC%` == 0.8)
dfrset9 = subset(dfr, dfr$`GC%` == 0.9)
dfrset10 = subset(dfr, dfr$`GC%` == 1)


ggplot(dfrset0,aes(x=`Mutations on Each Strain`,y=`Average CMs`,color=Kappa)) + geom_smooth() + theme_classic() + ggtitle("CMs vs Mutations for GC% = 0")
ggsave("cms_vs_muts_gc0.png",device = "png")
ggplot(dfrset1,aes(x=`Mutations on Each Strain`,y=`Average CMs`,color=Kappa)) + geom_smooth() + theme_classic() + ggtitle("CMs vs Mutations for GC% = 10")
ggsave("cms_vs_muts_gc10.png",device = "png")
ggplot(dfrset2,aes(x=`Mutations on Each Strain`,y=`Average CMs`,color=Kappa)) + geom_smooth() + theme_classic() + ggtitle("CMs vs Mutations for GC% = 20")
ggsave("cms_vs_muts_gc20.png",device = "png")
ggplot(dfrset3,aes(x=`Mutations on Each Strain`,y=`Average CMs`,color=Kappa)) + geom_smooth() + theme_classic() + ggtitle("CMs vs Mutations for GC% = 30")
ggsave("cms_vs_muts_gc30.png",device = "png")
ggplot(dfrset4,aes(x=`Mutations on Each Strain`,y=`Average CMs`,color=Kappa)) + geom_smooth() + theme_classic() + ggtitle("CMs vs Mutations for GC% = 40")
ggsave("cms_vs_muts_gc40.png",device = "png")
ggplot(dfrset5,aes(x=`Mutations on Each Strain`,y=`Average CMs`,color=Kappa)) + geom_smooth() + theme_classic() + ggtitle("CMs vs Mutations for GC% = 50")
ggsave("cms_vs_muts_gc50.png",device = "png")
ggplot(dfrset6,aes(x=`Mutations on Each Strain`,y=`Average CMs`,color=Kappa)) + geom_smooth() + theme_classic() + ggtitle("CMs vs Mutations for GC% = 60")
ggsave("cms_vs_muts_gc60.png",device = "png")
ggplot(dfrset7,aes(x=`Mutations on Each Strain`,y=`Average CMs`,color=Kappa)) + geom_smooth() + theme_classic() + ggtitle("CMs vs Mutations for GC% = 70")
ggsave("cms_vs_muts_gc70.png",device = "png")
ggplot(dfrset8,aes(x=`Mutations on Each Strain`,y=`Average CMs`,color=Kappa)) + geom_smooth() + theme_classic() + ggtitle("CMs vs Mutations for GC% = 80")
ggsave("cms_vs_muts_gc80.png",device = "png")
ggplot(dfrset9,aes(x=`Mutations on Each Strain`,y=`Average CMs`,color=Kappa)) + geom_smooth() + theme_classic() + ggtitle("CMs vs Mutations for GC% = 90")
ggsave("cms_vs_muts_gc90.png",device = "png")
ggplot(dfrset10,aes(x=`Mutations on Each Strain`,y=`Average CMs`,color=Kappa)) + geom_smooth() + theme_classic() + ggtitle("CMs vs Mutations for GC% = 100")
ggsave("cms_vs_muts_gc100.png",device = "png")

ggplot(dfr,aes(x=`Mutations on Each Strain`,y=`Average CMs`,color=Kappa)) + geom_smooth() + theme_classic() + ggtitle("CMs vs Mutations for variant GC%") + facet_wrap(~`GC%`)
ggsave("cms_vs_muts_facet.png",device = "png")